### ISSUE TITLE
Navigate programatically

### ISSUE THREAD

**Issue by pakjiddat** [dav-sea/EasyTab#4]
When I press the Tab button, the cursor moves to the next form field. The Tab button works fine. However, I would like the navigation to work on the click of a button. Please see below screenshot. When I click the button, the cursor should be  on the top most text field. When I click the button again, the cursor should move to the dropdown. When I click the button again the cursor should move to the bottom text field.

![screenshot-1](https://github.com/user-attachments/assets/c3caa318-a1b4-40f2-84b4-e39a9a365577)

I called this function in the button click handler: `EasyTabIntegration.Globally.Navigate();`, but it did not work. When I click on the button, the cursor moves to the top most text field. When I click on the button again, the cursor stays on the top most text field.

Thanks

**Comment by dav-sea** [comment]
Hello 👋

It seems that at the moment of clicking on the button, unity makes this button as current (This can be checked in the button click handler via `EventSystem.current.currentSelectedGameObject`), accordingly, `Navigate` will switch to the next element relative to this button, in this case it is a text field on top.

An event about changing the current in EventSystem object would help a lot, but I didn't find anything suitable.

Nevertheless, your task can be solved very simply if you save the currently selected object separately from the EventSystem. Then you can define the next one via `EasyTabIntegration.Globally.Solver.GetNext(current)`. 

In the generalized case, you will need to save the currently selected object to a temporary field. For example, like this script for button:

<details>
<summary> HandlerForButton.cs </summary>

```csharp
    private GameObject _current;
    
    void Start() { 
        GetComponent<Button>().onClick.AddListener(() =>
        {
            var easyTabSolver = new EasyTabSolver();
            var next = easyTabSolver.GetNext(_current);
            if(next && next.TryGetComponent(out Selectable nextSelectable))
                nextSelectable.Select();
        });
    }

    void Update() {
        var eventSystemCurrent = EventSystem.current.currentSelectedGameObject;
        if(eventSystemCurrent == gameObject) // gameObject is this button
            return;

        _current = eventSystemCurrent;
    }
```
</details>

If you need to exclude a button from navigation, you can do this by hanging the `EasyTab` component on it and changing `SelectableRecognition` to `AsNotSelectable`

**Result**:
![demo](https://github.com/user-attachments/assets/fa6d7e97-5328-41bd-893b-af972843bcc8)


I hope my answer was helpful.

**Comment by pakjiddat** [comment]
Hello

I attached the script you provided to the button object. I wanted to exclude the button from navigation so I attached EasyTab script to the button and set the `SelectableRecognition` property to `AsNotSelectable`. The navigation worked perfectly.

However I wanted the first text field to have focus set. I created a gameObject and attached the following script to it:

```

using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class SetFocus : MonoBehaviour
{
    public InputField myInputField;

    void Start()
    {
        // Set focus on the input field at the start of the scene
        SetInputFieldFocus();
    }

    void SetInputFieldFocus()
    {
        // Check if the input field is not already selected
        if (myInputField != null)
        {
            // Set the input field as the selected object in the EventSystem
            EventSystem.current.SetSelectedGameObject(myInputField.gameObject);

            // Optionally, activate the input field to immediately show the cursor
            myInputField.ActivateInputField();
        }
    }
}

```

I also attached the first text field to the above script from the inspector. After this, the first text field was focused.

Thank you very much for your help

**Comment by dav-sea** [comment]
You may also want to use `FirstSelected` in the `EventSystem` component to select a inputfield at the start

![image](https://github.com/user-attachments/assets/e0de46f3-cec6-4026-8674-396faa8abd19)

**Comment by pakjiddat** [comment]
Setting `FirstSelected` in `EventSystem` component allows setting input field that should have focus at the start. If I do this, then I dont need to use the SetFocus class that I posted. Thanks.
